### ISSUE TITLE
fcct allows duplicate files but Fedora CoreOS Ignition does not

### ISSUE THREAD

**Issue by dharmab** [coreos/fcct#95] opened 2020-04-19 19:00 UTC
`fcct` allows the same file path to be defined multiple times in a `storage.files` section, and will happily transpile an Ignition file. However, Fedora CoreOS does not accept duplicate file paths in the Ignition file in the `storage.files` section, and Ignition will fail if the user attempts to use such a file.

`fcct` should print an error and fail when attempting to use multiple duplicate files.

**Comment by lucab** [comment] 2020-04-20 07:54
Thanks for the report.

Which version of `fcct` are you using? I think this may have been fixed with https://github.com/coreos/fcct/pull/93, which is not part of a released version.
Can you try with the binary built from the `master` branch? There is a pre-built amd64 container for this kind of manual testing at `quay.io/coreos/fcct:master`.

**Comment by bgilbert** [comment] 2020-05-05 08:15
Closing as duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/451.  If you're still seeing this on the master branch, please let us know.

**Closed by bgilbert** 2020-05-05 08:15 UTC
